In [16]:
import pandas as pd 
import numpy as np 
from pathlib import Path

In [17]:
import os
print(os.listdir())
BASE_DIR = Path(r"C:\Users\P LIKITH VARMA\Downloads\bluestock capstone dataset")

['.DS_Store', '.git', '.gitignore', 'data', 'data_exploration.ipynb', 'outputs', 'README.md', 'scripts']

In [22]:

fund_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\01_fund_master.csv')
nav_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\02_nav_history.csv')
aum_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\03_aum_by_fund_house.csv')
sip_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\04_monthly_sip_inflows.csv')
category_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\05_category_inflows.csv')
folio_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\06_industry_folio_count.csv')
performance_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\07_scheme_performance.csv')
txn_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\08_investor_transactions.csv')
holdings_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\09_portfolio_holdings.csv')
benchmark_df = pd.read_csv('C:\\Users\\P LIKITH VARMA\\Downloads\\bluestock capstone dataset\\10_benchmark_indices.csv')

In [23]:
#Shape if every table
datasets = {
    "Fund Master": fund_df,
    "NAV History": nav_df,
    "AUM": aum_df,
    "SIP": sip_df,
    "Category": category_df,
    "Folio": folio_df,
    "Performance": performance_df,
    "Transactions": txn_df,
    "Holdings": holdings_df,
    "Benchmark": benchmark_df
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

Fund Master: (40, 15)
NAV History: (46000, 3)
AUM: (90, 5)
SIP: (48, 6)
Category: (144, 3)
Folio: (21, 6)
Performance: (40, 19)
Transactions: (32778, 13)
Holdings: (322, 8)
Benchmark: (8050, 3)

In [14]:
fund_df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [15]:
holdings_df.tail(4)

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
318,149324,BHARTIARTL,Bharti Airtel Ltd,Telecom,1.79,969.71,924.41,2025-12-31
319,149324,TCS,Tata Consultancy Services,IT,13.17,1637.69,1927.89,2025-12-31
320,149324,INDUSINDBK,IndusInd Bank Ltd,Banking,7.63,1387.30,3208.86,2025-12-31
321,149324,NTPC,NTPC Ltd,Utilities,2.04,1303.55,5797.95,2025-12-31

In [ ]:
#summary of fund_df table
fund_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB

In [ ]:
#finding null values
for name, df in datasets.items():
    print("\n")
    print("="*50)
    print(name)
    print(df.isnull().sum())

==================================================
Fund Master
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64


==================================================
NAV History
amfi_code    0
date         0
nav          0
dtype: int64


==================================================
AUM
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64


==================================================
SIP
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64


==================================================
Category
month               0
category            0
net_inflow_crore    0
dtype: int64


==================================================
Folio
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64


==================================================
Performance
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64


==================================================
Transactions
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64


==================================================
Holdings
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64


==================================================
Benchmark
date           0
index_name     0
close_value    0
dtype: int64

In [ ]:
#finding duplicate rows
for name, df in datasets.items():
    print(name, ":", df.duplicated().sum())

Fund Master : 0
NAV History : 0
AUM : 0
SIP : 0
Category : 0
Folio : 0
Performance : 0
Transactions : 0
Holdings : 0
Benchmark : 0

In [ ]:
#summary datatable of every dataset
summary = []

for name, df in datasets.items():
    summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicates": df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)
summary_df

        Dataset   Rows  Columns  Missing Values  Duplicates
0   Fund Master     40       15               0           0
1   NAV History  46000        3               0           0
2           AUM     90        5               0           0
3           SIP     48        6              12           0
4      Category    144        3               0           0
5         Folio     21        6               0           0
6   Performance     40       19               0           0
7  Transactions  32778       13               0           0
8      Holdings    322        8               0           0
9     Benchmark   8050        3               0           0

In [25]:
"""for name, df in datasets.items():
    print("\n" + "="*70)
    print(name)
    print("="*70)

    for col in df.columns:
        unique_count = df[col].nunique()

        if unique_count == len(df):
            print(f"{col} --> Possible Primary Key")"""

'for name, df in datasets.items():\n    print("\n" + "="*70)\n    print(name)\n    print("="*70)\n\n    for col in df.columns:\n        unique_count = df[col].nunique()\n\n        if unique_count == len(df):\n            print(f"{col} --> Possible Primary Key")'

In [22]:
data_dictionary = []

for name, df in datasets.items():
    for col in df.columns:
        data_dictionary.append({
            "Dataset": name,
            "Column": col,
            "Data Type": str(df[col].dtype),
            "Missing Values": df[col].isnull().sum(),
            "Unique Values": df[col].nunique()
        })

dictionary_df = pd.DataFrame(data_dictionary)

dictionary_df.head()

       Dataset        Column Data Type  Missing Values  Unique Values
0  Fund Master     amfi_code     int64               0             40
1  Fund Master    fund_house    object               0             10
2  Fund Master   scheme_name    object               0             40
3  Fund Master      category    object               0              2
4  Fund Master  sub_category    object               0             12

In [23]:
# Find common columns across datasets

column_map = {}

for name, df in datasets.items():
    for col in df.columns:
        if col not in column_map:
            column_map[col] = []
        column_map[col].append(name)

print("COMMON COLUMNS ACROSS DATASETS")
print("="*80)

for col, tables in column_map.items():
    if len(tables) > 1:
        print(f"\nColumn: {col}")
        print("Appears in:")
        for table in tables:
            print(f"   - {table}")

COMMON COLUMNS ACROSS DATASETS
================================================================================

Column: amfi_code
Appears in:
   - Fund Master
   - NAV History
   - Performance
   - Transactions
   - Holdings

Column: fund_house
Appears in:
   - Fund Master
   - AUM
   - Performance

Column: scheme_name
Appears in:
   - Fund Master
   - Performance

Column: category
Appears in:
   - Fund Master
   - Category
   - Performance

Column: plan
Appears in:
   - Fund Master
   - Performance

Column: expense_ratio_pct
Appears in:
   - Fund Master
   - Performance

Column: date
Appears in:
   - NAV History
   - AUM
   - Benchmark

Column: aum_crore
Appears in:
   - AUM
   - Performance

Column: month
Appears in:
   - SIP
   - Category
   - Folio

In [ ]:
#Finding unique coloumns or possible primary key columns
print("POTENTIAL PRIMARY KEYS")
print("="*80)

for name, df in datasets.items():

    print(f"\n{name}")

    for col in df.columns:

        unique_count = df[col].nunique()

        if unique_count == len(df):
            print(f"✓ {col} (Unique)")

POTENTIAL PRIMARY KEYS
================================================================================

Fund Master
✓ amfi_code (Unique)
✓ scheme_name (Unique)

NAV History

AUM

SIP
✓ month (Unique)
✓ sip_aum_lakh_crore (Unique)

Category

Folio
✓ month (Unique)
✓ total_folios_crore (Unique)
✓ equity_folios_crore (Unique)
✓ debt_folios_crore (Unique)
✓ others_folios_crore (Unique)

Performance
✓ amfi_code (Unique)
✓ scheme_name (Unique)
✓ return_3yr_pct (Unique)
✓ return_5yr_pct (Unique)
✓ benchmark_3yr_pct (Unique)
✓ aum_crore (Unique)

Transactions

Holdings
✓ market_value_cr (Unique)
✓ current_price_inr (Unique)

Benchmark

In [26]:
table_classification = {
    "Fund Master": "Dimension",
    "NAV History": "Fact",
    "AUM": "Fact",
    "SIP Inflows": "Fact",
    "Category Inflows": "Fact",
    "Folio Count": "Fact",
    "Scheme Performance": "Fact",
    "Investor Transactions": "Fact",
    "Portfolio Holdings": "Fact",
    "Benchmark Indices": "Fact"
}

classification_df = pd.DataFrame(
    list(table_classification.items()),
    columns=["Dataset", "Table Type"]
)

classification_df

                 Dataset Table Type
0            Fund Master  Dimension
1            NAV History       Fact
2                    AUM       Fact
3            SIP Inflows       Fact
4       Category Inflows       Fact
5            Folio Count       Fact
6     Scheme Performance       Fact
7  Investor Transactions       Fact
8     Portfolio Holdings       Fact
9      Benchmark Indices       Fact

In [29]:
import os

output_dir = "outputs"

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

classification_df.to_csv(
    os.path.join(output_dir, "table_classification.csv"),
    index=False
)

print("File saved successfully!")

File saved successfully!

In [31]:
observations = []

for name, df in datasets.items():

    observations.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

obs_df = pd.DataFrame(observations)

obs_df

        Dataset   Rows  Columns  Missing Values  Duplicate Rows
0   Fund Master     40       15               0               0
1   NAV History  46000        3               0               0
2           AUM     90        5               0               0
3           SIP     48        6              12               0
4      Category    144        3               0               0
5         Folio     21        6               0               0
6   Performance     40       19               0               0
7  Transactions  32778       13               0               0
8      Holdings    322        8               0               0
9     Benchmark   8050        3               0               0

In [33]:


obs_df.to_csv(
    os.path.join(output_dir, "day1_observations.csv"),
    index=False
)

In [34]:
relationship_data = []

for col, tables in column_map.items():

    if len(tables) > 1:

        relationship_data.append({
            "Column": col,
            "Appears In Tables": ", ".join(tables)
        })

relationship_df = pd.DataFrame(relationship_data)

relationship_df

              Column                                  Appears In Tables
0          amfi_code  Fund Master, NAV History, Performance, Transac...
1         fund_house                      Fund Master, AUM, Performance
2        scheme_name                           Fund Master, Performance
3           category                 Fund Master, Category, Performance
4               plan                           Fund Master, Performance
5  expense_ratio_pct                           Fund Master, Performance
6               date                        NAV History, AUM, Benchmark
7          aum_crore                                   AUM, Performance
8              month                               SIP, Category, Folio

In [35]:
relationship_df.to_csv(
    os.path.join(output_dir, "relationship_report.csv"),
    index=False
)

In [36]:
print("="*80)
print("DAY 1 PROJECT SUMMARY")
print("="*80)

print(f"Total Datasets Loaded: {len(datasets)}")

total_rows = sum(df.shape[0] for df in datasets.values())

print(f"Total Records: {total_rows:,}")

print("\nDatasets Processed:")

for name, df in datasets.items():
    print(f"✓ {name} ({df.shape[0]:,} rows)")

================================================================================
DAY 1 PROJECT SUMMARY
================================================================================
Total Datasets Loaded: 10
Total Records: 87,533

Datasets Processed:
✓ Fund Master (40 rows)
✓ NAV History (46,000 rows)
✓ AUM (90 rows)
✓ SIP (48 rows)
✓ Category (144 rows)
✓ Folio (21 rows)
✓ Performance (40 rows)
✓ Transactions (32,778 rows)
✓ Holdings (322 rows)
✓ Benchmark (8,050 rows)

In [39]:
classification_df.to_csv(
    os.path.join(output_dir, "table_classification.csv"),
    index=False
)



print("CSV saved successfully!")

CSV saved successfully!

Task 6 Explaore Fun master

In [2]:
from pathlib import Path
import pandas as pd

# Base Folder
BASE_DIR = Path(r"C:\Users\P LIKITH VARMA\Downloads\bluestock capstone dataset")

# File Paths
fund_master_path = BASE_DIR / "01_fund_master.csv"
nav_history_path = BASE_DIR / "02_nav_history.csv"

In [3]:
fund_master = pd.read_csv(fund_master_path)
nav_history = pd.read_csv(nav_history_path)

print("Fund Master Shape:", fund_master.shape)
print("NAV History Shape:", nav_history.shape)

Fund Master Shape: (40, 15)
NAV History Shape: (46000, 3)

In [4]:
print("Fund Master Columns")
print(fund_master.columns.tolist())

print("\nNAV History Columns")
print(nav_history.columns.tolist())

Fund Master Columns
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

NAV History Columns
['amfi_code', 'date', 'nav']

In [5]:
print("Number of Fund Houses:", fund_master["fund_house"].nunique())

fund_master["fund_house"].dropna().sort_values().unique()

print("Number of Categories:", fund_master["category"].nunique())

fund_master["category"].dropna().sort_values().unique()

print("Number of Sub-Categories:", fund_master["sub_category"].nunique())

fund_master["sub_category"].dropna().sort_values().unique()

Number of Fund Houses: 10
Number of Categories: 2
Number of Sub-Categories: 12

array(['ELSS', 'Flexi Cap', 'Gilt', 'Index', 'Index/ETF',
       'Large & Mid Cap', 'Large Cap', 'Liquid', 'Mid Cap',
       'Short Duration', 'Small Cap', 'Value'], dtype=object)

In [7]:
print("Number of Risk Categories:", fund_master["risk_category"].nunique())

fund_master["risk_category"].dropna().sort_values().unique()

amfi_codes = fund_master["amfi_code"].astype(str)

print("Total Records :", len(amfi_codes))
print("Unique Codes  :", amfi_codes.nunique())

amfi_codes.str.len().value_counts().sort_index()

fund_master["amfi_code"].head(20)

Number of Risk Categories: 5
Total Records : 40
Unique Codes  : 40

0     119551
1     119552
2     119598
3     119599
4     119120
5     100016
6     125497
7     100033
8     125498
9     100025
10    120503
11    120504
12    120505
13    120506
14    120507
15    118632
16    118633
17    118634
18    118635
19    118636
Name: amfi_code, dtype: int64

In [9]:
fund_codes = set(
    fund_master["amfi_code"]
    .dropna()
    .astype(str)
)

nav_codes = set(
    nav_history["amfi_code"]
    .dropna()
    .astype(str)
)

missing_codes = fund_codes - nav_codes

print("Missing Codes:", len(missing_codes))

list(missing_codes)[:20]

Missing Codes: 0

[]

In [10]:
coverage = (
    (len(fund_codes) - len(missing_codes))
    / len(fund_codes)
) * 100

print(f"Coverage = {coverage:.2f}%")

print("="*50)
print("DATA QUALITY SUMMARY")
print("="*50)

print(f"Fund Houses      : {fund_master['fund_house'].nunique()}")
print(f"Categories       : {fund_master['category'].nunique()}")
print(f"Sub-Categories   : {fund_master['sub_category'].nunique()}")
print(f"Risk Categories  : {fund_master['risk_category'].nunique()}")

print("\nAMFI Validation")
print("-"*50)

print(f"Fund Master Codes : {len(fund_codes)}")
print(f"NAV History Codes : {len(nav_codes)}")
print(f"Missing Codes     : {len(missing_codes)}")
print(f"Coverage          : {coverage:.2f}%")

if len(missing_codes) == 0:
    print("""
Data Quality Summary
--------------------
• All AMFI scheme codes in fund_master are present in nav_history.
• No missing AMFI codes were detected.
• Referential integrity between the two datasets is maintained.
• Dataset is suitable for NAV trend analysis and fund-level analytics.
""")
else:
    print(f"""
Data Quality Summary
--------------------
• {len(missing_codes)} AMFI codes from fund_master are missing in nav_history.
• Coverage: {coverage:.2f}%
• Missing codes should be investigated before analysis.
""")

Coverage = 100.00%
==================================================
DATA QUALITY SUMMARY
==================================================
Fund Houses      : 10
Categories       : 2
Sub-Categories   : 12
Risk Categories  : 5

AMFI Validation
--------------------------------------------------
Fund Master Codes : 40
NAV History Codes : 40
Missing Codes     : 0
Coverage          : 100.00%

Data Quality Summary
--------------------
• All AMFI scheme codes in fund_master are present in nav_history.
• No missing AMFI codes were detected.
• Referential integrity between the two datasets is maintained.
• Dataset is suitable for NAV trend analysis and fund-level analytics.